FROM python:3.8

# Create a directory where the code is to be hosted
RUN mkdir /app
# Define the working directory in the container
WORKDIR /app 

# Copy and install the requirements.
COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && \
    pip install -r requirements.txt
# Cython>=0.28.5
# numpy==1.23.0 
# Copy application code to the image
COPY . /app/

# Define environment variables
ENV dash_port=80
ENV dash_debug="False"

CMD ["python", "index.py"]